### ISSUE TITLE
Sound disabled error

### ISSUE THREAD

**Issue by maandree** [alexandre-mbm/dangerous-jack-connector#1]
If I run (from inside an X session)

```
canberra-gtk-play --file="/usr/share/sounds/freedesktop/stereo/suspend-error.oga"
```

the text

```
Failed to play sound: Sound disabled
```

is printed and and nothing else happens, except canberra-gtk-play exits with the value 1.

Any idea how to fix this?

Why does this package require X, it would be much more useful for me if it didn't
as I do not start X on my netbook.

**Comment by alexandre-mbm** [comment]
Did you have installed it by `yaourt` (in Arch Linux)? Or: which is the distro?
Dependencies the dependcies and more: `alsa` or `oss`, for exemple.

**Comment by maandree** [comment]
I just installed it from the AUR. The problem persists.
I have alsa, alsa-oss and pulse.

**Comment by alexandre-mbm** [comment]
~~Show me tail logs of `lspci`, `lsusb` and `dmesg` please.~~
Show me `lspci` and `lsusb` results, and the `dmese` tail please.

Xorg running? Which Windows Manager?

**Comment by maandree** [comment]
Yes Xorg is running with xmonad.

Nothing is added to lspci.
Nothing is added to lsusb. (I do not use USB for my audio, just standard audio jacks.) Also this is not a log.
Nothing is added to dmesg (or /dev/kmsg).

Sound is working perfectly in all other programs.

**Comment by maandree** [comment]
It works in Mate, but I do have mate-settings-daemon running in xmonad.

**Comment by maandree** [comment]
Instead of using DISPLAY=:0 you should search for the a DISPLAY that is running, and preferably running by the user if the user is not root so it can be tested. Sometimes I have a :1, but not a :0.

**Comment by maandree** [comment]
Workaround for all issues:

```
ffmpeg -i "$SOUND" -f wav - 2>/dev/null | aplay 2>/dev/null
```

**Comment by alexandre-mbm** [comment]
Comunity and @maandree, sorry my ignorance. I don't know the xmonad and I am using Gnome 3.

> Instead of using DISPLAY=:0 you should search for the a DISPLAY that is running

Yes, I knew it. Excuse me by I have did something specific for my system. I will accept pull requests with conditional flows. But note that **udev integration need run as root**, or not?

@maandree, can your workaround run as root? If yes, make a pull resquest please!

**Comment by maandree** [comment]
Of course, root can do anything (except run vlc, because the VLC dev:s do not what that.)

**Comment by alexandre-mbm** [comment]
I did not understand the point.

**Comment by maandree** [comment]
?

It will work as expected. There is not problem with it being run under root.

**Comment by alexandre-mbm** [comment]
Then make a pull request please. The historical will assign credits to you.
